[workspace]
resolver = "2"
members = [
    "crates/gpui",
    "crates/gpui_macros",
    "crates/gpui_util",
    "crates/gpui_shared_string",
    "crates/gpui_platform",
    "crates/gpui_macos",
    "crates/gpui_apple",
    "crates/gpui_linux",
    "crates/gpui_windows",
    "crates/gpui_wgpu",
    "crates/gpui_web",
    "crates/gpui_tokio",
    "crates/collections",
    "crates/scheduler",
    "crates/refineable",
    "crates/refineable/derive_refineable",
    "crates/sum_tree",
    "crates/util_macros",
    "crates/util",
    "crates/path",
    "crates/bench_metrics",
    "crates/http_client",
    "crates/http_client_tls",
    "crates/reqwest_client",
    "crates/ztracing",
    "crates/zlog",
    "crates/ztracing_macro",
    "tooling/perf",
]
default-members = ["crates/gpui"]

[workspace.package]
publish = false
edition = "2024"
